apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: davidsantander/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_HOST
              value: postgres-cluster-ip-service
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_NAME
              value: finance_db
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key:  DATABASE_PASSWORD
            